# k8s-manifests/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: n8n-secrets
  namespace: n8n
type: Opaque
stringData:
  N8N_DATABASE_USER: "n8nadmin"
  N8N_DATABASE_PASSWORD: "ChangeMePlease123!"  # Это будет заменено на значение из Key Vault
  N8N_ENCRYPTION_KEY: "n8n-encryption-key-placeholder"  # Это будет заменено на значение из Key Vault
