# k8s-manifests/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: n8n-service-account
  namespace: n8n
  labels:
    app: n8n
  annotations:
    azure.workload.identity/client-id: "AKS_MANAGED_IDENTITY_CLIENT_ID"  # Будет заменено на реальный ID
